/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apkbarber;

import java.awt.Color;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Alxxstrdy
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        wkt();
        
    }

        Timer t ;
        SimpleDateFormat st; 
        
    public void wkt(){

        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            Date dt = new Date();
            st = new SimpleDateFormat("HH:mm:ss" + " " + " " + "dd-MM-yyyy");
            String tt = st.format(dt);
            lJam.setText(tt);   
            
            }
        });
        
        t.start();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBelakang = new javax.swing.JPanel();
        pnAtas = new javax.swing.JPanel();
        lJam = new javax.swing.JLabel();
        sideBar = new javax.swing.JPanel();
        bHome = new Palette.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bReservasi = new Palette.Panel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bKasir = new Palette.Panel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bTransaksi = new Palette.Panel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bStok = new Palette.Panel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bReport = new Palette.Panel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bLogOut = new Palette.Panel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bList = new Palette.Panel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pnUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(223, 230, 233));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnBelakang.setBackground(new java.awt.Color(255, 255, 255));

        pnAtas.setPreferredSize(new java.awt.Dimension(898, 70));

        lJam.setBackground(new java.awt.Color(0, 0, 0));
        lJam.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        lJam.setText("jLabel15");

        javax.swing.GroupLayout pnAtasLayout = new javax.swing.GroupLayout(pnAtas);
        pnAtas.setLayout(pnAtasLayout);
        pnAtasLayout.setHorizontalGroup(
            pnAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAtasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lJam)
                .addContainerGap(652, Short.MAX_VALUE))
        );
        pnAtasLayout.setVerticalGroup(
            pnAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAtasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lJam)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        sideBar.setBackground(new java.awt.Color(46, 134, 222));

        bHome.setBackground(new java.awt.Color(46, 134, 222));
        bHome.setPreferredSize(new java.awt.Dimension(178, 30));
        bHome.setRoundBottomLeft(20);
        bHome.setRoundBottomRight(20);
        bHome.setRoundTopLeft(20);
        bHome.setRoundTopRight(20);
        bHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bHomeMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HOME");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N

        javax.swing.GroupLayout bHomeLayout = new javax.swing.GroupLayout(bHome);
        bHome.setLayout(bHomeLayout);
        bHomeLayout.setHorizontalGroup(
            bHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bHomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bHomeLayout.setVerticalGroup(
            bHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bReservasi.setBackground(new java.awt.Color(46, 134, 222));
        bReservasi.setPreferredSize(new java.awt.Dimension(178, 30));
        bReservasi.setRoundBottomLeft(20);
        bReservasi.setRoundBottomRight(20);
        bReservasi.setRoundTopLeft(20);
        bReservasi.setRoundTopRight(20);
        bReservasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bReservasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bReservasiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bReservasiMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RESERVASI");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/agenda.png"))); // NOI18N

        javax.swing.GroupLayout bReservasiLayout = new javax.swing.GroupLayout(bReservasi);
        bReservasi.setLayout(bReservasiLayout);
        bReservasiLayout.setHorizontalGroup(
            bReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bReservasiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bReservasiLayout.setVerticalGroup(
            bReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bKasir.setBackground(new java.awt.Color(46, 134, 222));
        bKasir.setPreferredSize(new java.awt.Dimension(178, 30));
        bKasir.setRoundBottomLeft(20);
        bKasir.setRoundBottomRight(20);
        bKasir.setRoundTopLeft(20);
        bKasir.setRoundTopRight(20);
        bKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bKasirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bKasirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bKasirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bKasirMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("KASIR");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cashier-machine.png"))); // NOI18N

        javax.swing.GroupLayout bKasirLayout = new javax.swing.GroupLayout(bKasir);
        bKasir.setLayout(bKasirLayout);
        bKasirLayout.setHorizontalGroup(
            bKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bKasirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bKasirLayout.setVerticalGroup(
            bKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bTransaksi.setBackground(new java.awt.Color(46, 134, 222));
        bTransaksi.setPreferredSize(new java.awt.Dimension(178, 30));
        bTransaksi.setRoundBottomLeft(20);
        bTransaksi.setRoundBottomRight(20);
        bTransaksi.setRoundTopLeft(20);
        bTransaksi.setRoundTopRight(20);
        bTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bTransaksiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bTransaksiMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TRANSAKSI");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transaction.png"))); // NOI18N

        javax.swing.GroupLayout bTransaksiLayout = new javax.swing.GroupLayout(bTransaksi);
        bTransaksi.setLayout(bTransaksiLayout);
        bTransaksiLayout.setHorizontalGroup(
            bTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bTransaksiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bTransaksiLayout.setVerticalGroup(
            bTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bStok.setBackground(new java.awt.Color(46, 134, 222));
        bStok.setPreferredSize(new java.awt.Dimension(178, 30));
        bStok.setRoundBottomLeft(20);
        bStok.setRoundBottomRight(20);
        bStok.setRoundTopLeft(20);
        bStok.setRoundTopRight(20);
        bStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bStokMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bStokMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("STOK");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ready-stock.png"))); // NOI18N

        javax.swing.GroupLayout bStokLayout = new javax.swing.GroupLayout(bStok);
        bStok.setLayout(bStokLayout);
        bStokLayout.setHorizontalGroup(
            bStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bStokLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bStokLayout.setVerticalGroup(
            bStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bReport.setBackground(new java.awt.Color(46, 134, 222));
        bReport.setPreferredSize(new java.awt.Dimension(178, 30));
        bReport.setRoundBottomLeft(20);
        bReport.setRoundBottomRight(20);
        bReport.setRoundTopLeft(20);
        bReport.setRoundTopRight(20);
        bReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bReportMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REPORT");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/report.png"))); // NOI18N

        javax.swing.GroupLayout bReportLayout = new javax.swing.GroupLayout(bReport);
        bReport.setLayout(bReportLayout);
        bReportLayout.setHorizontalGroup(
            bReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bReportLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bReportLayout.setVerticalGroup(
            bReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bLogOut.setBackground(new java.awt.Color(46, 134, 222));
        bLogOut.setRoundBottomLeft(20);
        bLogOut.setRoundBottomRight(20);
        bLogOut.setRoundTopLeft(20);
        bLogOut.setRoundTopRight(20);
        bLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bLogOutMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LOG OUT");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/turn-off.png"))); // NOI18N

        javax.swing.GroupLayout bLogOutLayout = new javax.swing.GroupLayout(bLogOut);
        bLogOut.setLayout(bLogOutLayout);
        bLogOutLayout.setHorizontalGroup(
            bLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bLogOutLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bLogOutLayout.setVerticalGroup(
            bLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        bList.setBackground(new java.awt.Color(46, 134, 222));
        bList.setPreferredSize(new java.awt.Dimension(178, 30));
        bList.setRoundBottomLeft(20);
        bList.setRoundBottomRight(20);
        bList.setRoundTopLeft(20);
        bList.setRoundTopRight(20);
        bList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bListMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bListMousePressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("LIST ");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/to-do-list.png"))); // NOI18N

        javax.swing.GroupLayout bListLayout = new javax.swing.GroupLayout(bList);
        bList.setLayout(bListLayout);
        bListLayout.setHorizontalGroup(
            bListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bListLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bListLayout.setVerticalGroup(
            bListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bReservasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bKasir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bStok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(bHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(bReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(bKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(bTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(bStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(bList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(bReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnUtama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnBelakangLayout = new javax.swing.GroupLayout(pnBelakang);
        pnBelakang.setLayout(pnBelakangLayout);
        pnBelakangLayout.setHorizontalGroup(
            pnBelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBelakangLayout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnBelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBelakangLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(pnBelakangLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pnAtas, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnBelakangLayout.setVerticalGroup(
            pnBelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBelakangLayout.createSequentialGroup()
                .addComponent(pnAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pnBelakang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHomeMouseEntered
        bHome.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_bHomeMouseEntered

    private void bHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHomeMouseExited
        bHome.setBackground(new Color(223,230,233));
    }//GEN-LAST:event_bHomeMouseExited

    private void bReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bReportMouseEntered
        bReport.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_bReportMouseEntered

    private void bReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bReportMouseExited
        bReport.setBackground(new Color(223,230,233));
    }//GEN-LAST:event_bReportMouseExited

    private void bLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogOutMouseEntered
        bLogOut.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_bLogOutMouseEntered

    private void bLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogOutMouseExited
        bLogOut.setBackground(new Color(223,230,233));
    }//GEN-LAST:event_bLogOutMouseExited

    private void bReservasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bReservasiMouseEntered
        bReservasi.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_bReservasiMouseEntered

    private void bReservasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bReservasiMouseExited
        bReservasi.setBackground(new Color(223,230,233));
    }//GEN-LAST:event_bReservasiMouseExited

    private void bKasirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKasirMouseEntered
        bKasir.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_bKasirMouseEntered

    private void bKasirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKasirMouseExited
        bKasir.setBackground(new Color(223,230,233));
    }//GEN-LAST:event_bKasirMouseExited

    private void bTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTransaksiMouseEntered
        bTransaksi.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_bTransaksiMouseEntered

    private void bTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTransaksiMouseExited
        bTransaksi.setBackground(new Color(223,230,233));
    }//GEN-LAST:event_bTransaksiMouseExited

    private void bStokMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bStokMouseEntered
        bStok.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_bStokMouseEntered

    private void bStokMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bStokMouseExited
        bStok.setBackground(new Color(223,230,233));
    }//GEN-LAST:event_bStokMouseExited

    private void bHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHomeMouseClicked
        bHome.setBackground(new Color(223,230,233));
        
        pnUtama.removeAll();
        pnUtama.add(new Menu());
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_bHomeMouseClicked

    private void bLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogOutMouseClicked
        new Loginsite().setVisible(true);
        dispose();
    }//GEN-LAST:event_bLogOutMouseClicked

    private void bKasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKasirMouseClicked

    }//GEN-LAST:event_bKasirMouseClicked

    private void bTransaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTransaksiMousePressed

    }//GEN-LAST:event_bTransaksiMousePressed

    private void bReservasiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bReservasiMousePressed
        bKasir.setBackground(new Color(223,230,233));
        
        pnUtama.removeAll();
        pnUtama.add(new Reservasi());
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_bReservasiMousePressed

    private void bKasirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKasirMousePressed
        bKasir.setBackground(new Color(223,230,233));
        
        pnUtama.removeAll();
        pnUtama.add(new Kasir());
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_bKasirMousePressed

    private void bListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bListMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bListMouseEntered

    private void bListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bListMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bListMouseExited

    private void bListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bListMousePressed
        bList.setBackground(new Color(223,230,233));
        
        pnUtama.removeAll();
        pnUtama.add(new PriceList() );
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_bListMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Palette.Panel bHome;
    private Palette.Panel bKasir;
    private Palette.Panel bList;
    private Palette.Panel bLogOut;
    private Palette.Panel bReport;
    private Palette.Panel bReservasi;
    private Palette.Panel bStok;
    private Palette.Panel bTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lJam;
    private javax.swing.JPanel pnAtas;
    private javax.swing.JPanel pnBelakang;
    private javax.swing.JPanel pnUtama;
    private javax.swing.JPanel sideBar;
    // End of variables declaration//GEN-END:variables

    private Color Color(int i, int i0, int i1) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
