/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package apkbarber;

import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alxxstrdy
 */
   
public class Kasir extends javax.swing.JPanel {

    /**
     * Creates new form Kasir
     */

    private int total=0;
    
    public Kasir() {
        initComponents();
    }
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnPricelist = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnTambah = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(730, 564));
        setLayout(new java.awt.CardLayout());

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setLayout(new java.awt.CardLayout());

        pnPricelist.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("BUAT TRANSAKSI");

        javax.swing.GroupLayout pnPricelistLayout = new javax.swing.GroupLayout(pnPricelist);
        pnPricelist.setLayout(pnPricelistLayout);
        pnPricelistLayout.setHorizontalGroup(
            pnPricelistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPricelistLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(593, Short.MAX_VALUE))
        );
        pnPricelistLayout.setVerticalGroup(
            pnPricelistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPricelistLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(527, Short.MAX_VALUE))
        );

        pnMain.add(pnPricelist, "card2");

        pnTambah.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnTambahLayout = new javax.swing.GroupLayout(pnTambah);
        pnTambah.setLayout(pnTambahLayout);
        pnTambahLayout.setHorizontalGroup(
            pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        pnTambahLayout.setVerticalGroup(
            pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        pnMain.add(pnTambah, "card3");

        add(pnMain, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnPricelist;
    private javax.swing.JPanel pnTambah;
    // End of variables declaration//GEN-END:variables
}
