/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apkbarber;

import com.formdev.flatlaf.FlatLightLaf;
import com.mysql.cj.jdbc.PreparedStatementWrapper;
import config.koneksi;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.security.MessageDigest;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


/**
 *
 * @author Alxxstrdy
 */
public class Loginsite extends javax.swing.JFrame {
    int xx, xy;
    private Connection conn;
    /**
     * Creates new form Loginsite
     */
    public Loginsite() {
        initComponents();
        conn = koneksi.getConnection();
        this.setBackground(new Color(0, 0, 0, 0));
        ilang();
        setShowPassword();
    }
    
    void ilang (){
        wPassword.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Belakang = new Palette.Panel();
        close = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tpassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bLogin = new Palette.Panel();
        jLabel7 = new javax.swing.JLabel();
        tusername = new javax.swing.JTextField();
        wPassword = new javax.swing.JLabel();
        eyeHide = new javax.swing.JLabel();
        eye = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icon/Barbericn.png")).getImage());
        setUndecorated(true);

        Belakang.setBackground(new java.awt.Color(223, 230, 233));
        Belakang.setRoundBottomLeft(30);
        Belakang.setRoundBottomRight(30);
        Belakang.setRoundTopLeft(30);
        Belakang.setRoundTopRight(30);
        Belakang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BelakangMouseDragged(evt);
            }
        });
        Belakang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BelakangMousePressed(evt);
            }
        });

        close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        close.setText("X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/LogoBarber.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 36)); // NOI18N
        jLabel3.setText("LOGIN");

        jLabel4.setFont(new java.awt.Font("Rage Italic", 0, 18)); // NOI18N
        jLabel4.setText("Welcome Back");

        tpassword.setBackground(new java.awt.Color(223, 230, 233));
        tpassword.setText("Password");
        tpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tpasswordFocusLost(evt);
            }
        });
        tpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpasswordActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 12)); // NOI18N
        jLabel5.setText("USERNAME");

        jLabel6.setFont(new java.awt.Font("Humanst521 BT", 1, 12)); // NOI18N
        jLabel6.setText("PASSWORD");

        bLogin.setBackground(new java.awt.Color(214, 48, 49));
        bLogin.setRoundBottomRight(20);
        bLogin.setRoundTopLeft(20);
        bLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bLoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bLoginMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LOGIN");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout bLoginLayout = new javax.swing.GroupLayout(bLogin);
        bLogin.setLayout(bLoginLayout);
        bLoginLayout.setHorizontalGroup(
            bLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
        );
        bLoginLayout.setVerticalGroup(
            bLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        tusername.setBackground(new java.awt.Color(223, 230, 233));
        tusername.setText("Username");
        tusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tusernameFocusLost(evt);
            }
        });

        wPassword.setFont(new java.awt.Font("Humanst521 BT", 1, 12)); // NOI18N
        wPassword.setForeground(new java.awt.Color(255, 0, 0));
        wPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wPassword.setText("jLabel8");

        eyeHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/eye hide.png"))); // NOI18N

        eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/eye.png"))); // NOI18N

        javax.swing.GroupLayout BelakangLayout = new javax.swing.GroupLayout(Belakang);
        Belakang.setLayout(BelakangLayout);
        BelakangLayout.setHorizontalGroup(
            BelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BelakangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close)
                .addGap(10, 10, 10))
            .addGroup(BelakangLayout.createSequentialGroup()
                .addGroup(BelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BelakangLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(BelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BelakangLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(BelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(BelakangLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel4))))
                            .addComponent(tpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(tusername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eyeHide, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BelakangLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(BelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(BelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BelakangLayout.createSequentialGroup()
                    .addContainerGap(352, Short.MAX_VALUE)
                    .addComponent(eye)
                    .addGap(288, 288, 288)))
        );
        BelakangLayout.setVerticalGroup(
            BelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BelakangLayout.createSequentialGroup()
                .addGroup(BelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BelakangLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2))
                    .addGroup(BelakangLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tusername, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eyeHide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(bLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wPassword)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(BelakangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BelakangLayout.createSequentialGroup()
                    .addContainerGap(280, Short.MAX_VALUE)
                    .addComponent(eye, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(147, 147, 147)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Belakang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Belakang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BelakangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BelakangMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_BelakangMousePressed

    private void BelakangMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BelakangMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_BelakangMouseDragged

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        dispose();
    }//GEN-LAST:event_closeMousePressed

    private void bLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLoginMouseEntered
        bLogin.setBackground(new Color(134, 26, 27));
    }//GEN-LAST:event_bLoginMouseEntered

    private void bLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLoginMouseExited
        bLogin.setBackground(new Color(214,48,49));
    }//GEN-LAST:event_bLoginMouseExited

    private void bLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLoginMousePressed
        bLogin.setBackground(new Color(222, 91, 91));
        prosesLogin();
    }//GEN-LAST:event_bLoginMousePressed

    private void bLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLoginMouseClicked

    }//GEN-LAST:event_bLoginMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_closeMouseExited

    private void tusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tusernameFocusGained
        if (tusername.getText().equals("Username")){
            tusername.setText("");
        }
    }//GEN-LAST:event_tusernameFocusGained

    private void tusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tusernameFocusLost
        if (tusername.getText().equals("")){
            tusername.setText("Username");
        }
    }//GEN-LAST:event_tusernameFocusLost

    private void tpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpasswordActionPerformed

    private void tpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tpasswordFocusGained
        if (tpassword.getText().equals("Password")){
            tpassword.setText("");
        }
    }//GEN-LAST:event_tpasswordFocusGained

    private void tpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tpasswordFocusLost
        if (tpassword.getText().equals("")){
            tpassword.setText("Password");
        }
    }//GEN-LAST:event_tpasswordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
         UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginsite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Palette.Panel Belakang;
    private Palette.Panel bLogin;
    private javax.swing.JLabel close;
    private javax.swing.JLabel eye;
    private javax.swing.JLabel eyeHide;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField tpassword;
    private javax.swing.JTextField tusername;
    private javax.swing.JLabel wPassword;
    // End of variables declaration//GEN-END:variables
private String getMd5java(String message){
    String digest = null;
    try {
        MessageDigest md = MessageDigest.getInstance("MD5");
        byte[] hash = md.digest(message.getBytes("UTF-8"));
        
        StringBuilder sb = new StringBuilder(2*hash.length);
        for(byte b : hash) {
            sb.append(String.format("%02x", b & 0xff));
        }
        digest = sb.toString();
        
    } catch (Exception e) {
        Logger.getLogger(Loginsite.class.getName()).log(Level.SEVERE, null, e );
                
    }
    return digest;
}   
private boolean validasiInput(){
    boolean valid = false;
    if (tusername.getText().trim().isEmpty()){
        wPassword.setText("Username tidak boleh kosong");
    }else if (tpassword.getText().trim().isEmpty()){
        wPassword.setText("Password tidak boleh kosong");
    }else{
        valid=true;
    }
    return valid;
}
private boolean checklogin(String username, String password){
    if(conn != null){
        try {
            String sql= "SELECT *FROM user WHERE Username=? AND Password=?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, username);
            st.setString(2, password);
            
            ResultSet rs = st.executeQuery();
            if(rs.next()){
                return true;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    return false;
}
private void prosesLogin(){
    if (validasiInput()){
        String username = tusername.getText();
        String password = new String(tpassword.getPassword());
        String hashedPassword = getMd5java(password);
        
        if(checklogin(username, hashedPassword)){
            MenuUtama mn = new MenuUtama();
            mn.setVisible(true);
            mn.revalidate();
            
            dispose();
        }else {
            wPassword.setText("Username/Password salah");
            tusername.setText("Username");
            tpassword.setText("Password");
        }
    }
}

    private void setShowPassword() {
        eyeHide.setVisible(false);
        eye.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e) {
                eye.setVisible(false);
                eyeHide.setVisible(true);
                tpassword.setEchoChar((char)0);
            }
        
        });
                eyeHide.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e) {
                eye.setVisible(true);
                eyeHide.setVisible(false);
                tpassword.setEchoChar('*');
            }
        
        });
        
    }
}   
