/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package apkbarber;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import config.koneksi;
import java.awt.Color;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.JOptionPane;
import popup.BerhasilDiubah;
import popup.PeringatanPassLama;
import popup.PeringatanTidakcocok;

/**
 *
 * @author Alxxstrdy
 */
public class PergantianPass extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */

    private Connection conn;
    private String userID;

    public PergantianPass(String userID) {
        initComponents();
        conn = (Connection) koneksi.getConnection();
        this.userID = userID;
        tUserName.setText(getUserID());
        tUserName.setEnabled(false);
        

    }
     public String getUserID() {
     return userID;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnAdd = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tPassLama = new javax.swing.JPasswordField();
        tPassBaru = new javax.swing.JPasswordField();
        tKomfirmPass = new javax.swing.JPasswordField();
        tUserName = new javax.swing.JLabel();
        bSave = new Palette.Panel();
        lsave = new javax.swing.JLabel();
        bCancel = new Palette.Panel();
        lbatal = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        pnMain.setLayout(new java.awt.CardLayout());

        pnAdd.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("PERGANTIAN PASSWORD");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("USERNAME");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("PASSWORD LAMA");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("PASSWORD BARU");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("KONFIRMASI PASSWORD");

        tUserName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tUserName.setText("jLabel1");

        bSave.setBackground(new java.awt.Color(2, 131, 145));
        bSave.setFocusCycleRoot(true);
        bSave.setRoundBottomLeft(10);
        bSave.setRoundBottomRight(10);
        bSave.setRoundTopLeft(10);
        bSave.setRoundTopRight(10);
        bSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bSaveMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bSaveMousePressed(evt);
            }
        });

        lsave.setFont(new java.awt.Font("NEXT ART", 0, 14)); // NOI18N
        lsave.setForeground(new java.awt.Color(255, 255, 255));
        lsave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lsave.setText("SIMPAN");
        lsave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout bSaveLayout = new javax.swing.GroupLayout(bSave);
        bSave.setLayout(bSaveLayout);
        bSaveLayout.setHorizontalGroup(
            bSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lsave, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );
        bSaveLayout.setVerticalGroup(
            bSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lsave, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        bCancel.setBackground(new java.awt.Color(214, 48, 49));
        bCancel.setFocusCycleRoot(true);
        bCancel.setRoundBottomLeft(10);
        bCancel.setRoundBottomRight(10);
        bCancel.setRoundTopLeft(10);
        bCancel.setRoundTopRight(10);
        bCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bCancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bCancelMousePressed(evt);
            }
        });

        lbatal.setFont(new java.awt.Font("NEXT ART", 0, 14)); // NOI18N
        lbatal.setForeground(new java.awt.Color(255, 255, 255));
        lbatal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbatal.setText("BATAl");
        lbatal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout bCancelLayout = new javax.swing.GroupLayout(bCancel);
        bCancel.setLayout(bCancelLayout);
        bCancelLayout.setHorizontalGroup(
            bCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbatal, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );
        bCancelLayout.setVerticalGroup(
            bCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbatal, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnAddLayout = new javax.swing.GroupLayout(pnAdd);
        pnAdd.setLayout(pnAddLayout);
        pnAddLayout.setHorizontalGroup(
            pnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tUserName)
                    .addComponent(jLabel14)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(tPassBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tKomfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tPassLama, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(322, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAddLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        pnAddLayout.setVerticalGroup(
            pnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(99, 99, 99)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tUserName)
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addGap(7, 7, 7)
                .addComponent(tPassLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPassBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(13, 13, 13)
                .addComponent(tKomfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(pnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pnMain.add(pnAdd, "card4");

        add(pnMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSaveMouseEntered
        bSave.setBackground(new Color (2,154,170));
    }//GEN-LAST:event_bSaveMouseEntered

    private void bSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSaveMouseExited
        bSave.setBackground(new Color (2,131,145));
    }//GEN-LAST:event_bSaveMouseExited

    private void bSaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSaveMousePressed
       pergantianPassword();
    }//GEN-LAST:event_bSaveMousePressed

    private void bCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelMouseEntered
        bCancel.setBackground(new Color(218,69,70));
    }//GEN-LAST:event_bCancelMouseEntered

    private void bCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelMouseExited
        bCancel.setBackground(new Color(214,48,49));
    }//GEN-LAST:event_bCancelMouseExited

    private void bCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelMousePressed
        pnMain.removeAll();
        pnMain.add(new Home(userID));
        pnMain.repaint();
        pnMain.revalidate();
    }//GEN-LAST:event_bCancelMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Palette.Panel bCancel;
    private Palette.Panel bSave;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbatal;
    private javax.swing.JLabel lsave;
    private javax.swing.JPanel pnAdd;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPasswordField tKomfirmPass;
    private javax.swing.JPasswordField tPassBaru;
    private javax.swing.JPasswordField tPassLama;
    private javax.swing.JLabel tUserName;
    // End of variables declaration//GEN-END:variables

    
  private void  resetForm(){
      tPassLama.setText("Password");
      tPassBaru.setText("Password");
      tKomfirmPass.setText("Password");
  }
    
public boolean validateOldPassword(String username, String oldPassword) {


    String encryptedOldPassword = Loginsite.getMd5Java(oldPassword);
    // return userDao.validateOldPassword(Koneksi.getConnection(), username, encryptedOldPassword);
    try {
        String sql =  "SELECT *FROM user WHERE username=? AND  password =?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, username);
        pstmt.setString(2, encryptedOldPassword);
        ResultSet rs = pstmt.executeQuery();
        return rs.next();
    } catch (SQLException ex) {
        ex.printStackTrace();
        return false;
    }
}


public boolean changePassword(String username, String oldPassword, String newPassword) {
    String encryptedOldPassword =Loginsite.getMd5Java(oldPassword);
    String encryptedNewPassword = Loginsite.getMd5Java(newPassword);
    try {
        String sql = "SELECT *FROM user WHERE username=? AND  password =?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, username);
        pstmt.setString(2, encryptedOldPassword);
        ResultSet rs = pstmt.executeQuery();
        

        
        if (rs.next()) {
            String sqlUpdate = "UPDATE user SET password= ? WHERE username = ?";
            PreparedStatement pstmtUpdate = conn.prepareStatement(sqlUpdate);
            pstmtUpdate.setString(1, encryptedNewPassword);
            pstmtUpdate.setString(2, username);
            int result = pstmtUpdate.executeUpdate();
            return result > 0;
        } else {
            return false;
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        return false;
    }
}

private void pergantianPassword(){

    String username = tUserName.getText();
    String passLama = tPassLama.getText();
    String passBaru = tPassBaru.getText();
    String konfirmPassBaru = tKomfirmPass.getText();

    if (!passBaru.equals(konfirmPassBaru)) {
        boolean closable = true;
        PeringatanTidakcocok data = new PeringatanTidakcocok(null, closable);
        data.setVisible(true);
        return;
    }

    if (!validateOldPassword(username, passLama)) {
        boolean closable = true;
        PeringatanPassLama data = new PeringatanPassLama(null, closable);
        data.setVisible(true);
        return;
    }

    if (changePassword(username, passLama, passBaru)) {
        boolean closable = true;
        BerhasilDiubah data = new BerhasilDiubah(null, closable);
        data.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(null, "Password gagal diubah");
    }

    resetForm();
}

            

}
