/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package apkbarber;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alxxstrdy
 */
public class PriceList extends javax.swing.JPanel {

    /**
     * Creates new form PriceList
     */
    public PriceList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnPricelist = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vTabel = new Palette.JTable_Custom();
        bCancel2 = new Palette.Panel();
        jLabel16 = new javax.swing.JLabel();
        bSelesai = new Palette.Panel();
        jLabel12 = new javax.swing.JLabel();
        bTambah = new Palette.Panel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnTambah = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        tHarga = new javax.swing.JTextField();
        bCAncel = new Palette.Panel();
        jLabel6 = new javax.swing.JLabel();
        bSelesaii = new Palette.Panel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setLayout(new java.awt.CardLayout());

        pnPricelist.setBackground(new java.awt.Color(255, 255, 255));

        vTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Barang/Jasa", "Nama ", "Harga"
            }
        ));
        vTabel.setRowHeight(20);
        vTabel.setShowVerticalLines(true);
        jScrollPane2.setViewportView(vTabel);

        bCancel2.setBackground(new java.awt.Color(255, 51, 51));
        bCancel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCancel2MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("CANCEL");

        javax.swing.GroupLayout bCancel2Layout = new javax.swing.GroupLayout(bCancel2);
        bCancel2.setLayout(bCancel2Layout);
        bCancel2Layout.setHorizontalGroup(
            bCancel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );
        bCancel2Layout.setVerticalGroup(
            bCancel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bCancel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        bSelesai.setBackground(new java.awt.Color(0, 153, 153));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("SELESAI");

        javax.swing.GroupLayout bSelesaiLayout = new javax.swing.GroupLayout(bSelesai);
        bSelesai.setLayout(bSelesaiLayout);
        bSelesaiLayout.setHorizontalGroup(
            bSelesaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );
        bSelesaiLayout.setVerticalGroup(
            bSelesaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bSelesaiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        bTambah.setBackground(new java.awt.Color(102, 255, 51));
        bTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bTambahMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TAMBAH");

        javax.swing.GroupLayout bTambahLayout = new javax.swing.GroupLayout(bTambah);
        bTambah.setLayout(bTambahLayout);
        bTambahLayout.setHorizontalGroup(
            bTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );
        bTambahLayout.setVerticalGroup(
            bTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bTambahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("DAFTAR LIST BARANG DAN JASA");

        javax.swing.GroupLayout pnPricelistLayout = new javax.swing.GroupLayout(pnPricelist);
        pnPricelist.setLayout(pnPricelistLayout);
        pnPricelistLayout.setHorizontalGroup(
            pnPricelistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPricelistLayout.createSequentialGroup()
                .addContainerGap(380, Short.MAX_VALUE)
                .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(bCancel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(pnPricelistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnPricelistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnPricelistLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnPricelistLayout.setVerticalGroup(
            pnPricelistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPricelistLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addGroup(pnPricelistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bTambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSelesai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(pnPricelistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnPricelistLayout.createSequentialGroup()
                    .addGap(152, 152, 152)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(152, Short.MAX_VALUE)))
        );

        pnMain.add(pnPricelist, "card2");

        pnTambah.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("INPUT BARANG/JASA");

        tID.setText("ID Barang/Jasa");
        tID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tIDFocusLost(evt);
            }
        });
        tID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIDActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("ID BARANG/JASA");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("NAMA BARANG/JASA");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("HARGA");

        tNama.setText("Nama Barang/Jasa");
        tNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tNamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tNamaFocusLost(evt);
            }
        });
        tNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaActionPerformed(evt);
            }
        });

        tHarga.setText("Harga");
        tHarga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tHargaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tHargaFocusLost(evt);
            }
        });
        tHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHargaActionPerformed(evt);
            }
        });

        bCAncel.setBackground(new java.awt.Color(255, 0, 0));
        bCAncel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCAncelMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CANCEL");

        javax.swing.GroupLayout bCAncelLayout = new javax.swing.GroupLayout(bCAncel);
        bCAncel.setLayout(bCAncelLayout);
        bCAncelLayout.setHorizontalGroup(
            bCAncelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bCAncelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bCAncelLayout.setVerticalGroup(
            bCAncelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        bSelesaii.setBackground(new java.awt.Color(0, 153, 153));
        bSelesaii.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bSelesaiiMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SELESAI");

        javax.swing.GroupLayout bSelesaiiLayout = new javax.swing.GroupLayout(bSelesaii);
        bSelesaii.setLayout(bSelesaiiLayout);
        bSelesaiiLayout.setHorizontalGroup(
            bSelesaiiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );
        bSelesaiiLayout.setVerticalGroup(
            bSelesaiiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnTambahLayout = new javax.swing.GroupLayout(pnTambah);
        pnTambah.setLayout(pnTambahLayout);
        pnTambahLayout.setHorizontalGroup(
            pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTambahLayout.createSequentialGroup()
                .addContainerGap(451, Short.MAX_VALUE)
                .addComponent(bSelesaii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(bCAncel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(pnTambahLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(tNama)
                        .addComponent(tID)
                        .addComponent(tHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTambahLayout.setVerticalGroup(
            pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTambahLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel4)
                .addGap(42, 42, 42)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(pnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCAncel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSelesaii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pnMain.add(pnTambah, "card3");

        add(pnMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bCancel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancel2MouseClicked
        pnMain.removeAll();
        pnMain.add(new Menu()); // Assuming HomePanel is the class for the home screen
        pnMain.repaint();
        pnMain.revalidate();
    }//GEN-LAST:event_bCancel2MouseClicked

    private void bTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTambahMouseClicked
        pnMain.removeAll();
        pnMain.add(pnTambah);
        pnMain.repaint();;
        pnMain.revalidate();
    }//GEN-LAST:event_bTambahMouseClicked

    private void tIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tIDFocusGained
        if (tID.getText().equals("ID Pelanggan")) {
            tID.setText("");
        }
    }//GEN-LAST:event_tIDFocusGained

    private void tIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tIDFocusLost
        if (tID.getText().equals("")) {
            tID.setText("ID Pelanggan");
        }
    }//GEN-LAST:event_tIDFocusLost

    private void tIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIDActionPerformed

    private void tHargaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tHargaFocusGained
        if (tHarga.getText().equals("No Telp")) {
            tHarga.setText("");
        }
    }//GEN-LAST:event_tHargaFocusGained

    private void tHargaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tHargaFocusLost
        if (tHarga.getText().equals("")) {
            tHarga.setText("No Telp");
        }
    }//GEN-LAST:event_tHargaFocusLost

    private void tHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tHargaActionPerformed

    private void tNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tNamaFocusGained
        if (tNama.getText().equals("Nama Pelanggan")) {
            tNama.setText("");
        }
    }//GEN-LAST:event_tNamaFocusGained

    private void tNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tNamaFocusLost
        if (tNama.getText().equals("")) {
            tNama.setText("Nama Pelanggan");
        }
    }//GEN-LAST:event_tNamaFocusLost

    private void tNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaActionPerformed

    private void bCAncelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCAncelMouseClicked
        pnMain.removeAll();
        pnMain.add(pnPricelist);
        pnMain.repaint();
        pnMain.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_bCAncelMouseClicked

    private void bSelesaiiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSelesaiiMousePressed
            vTabel.setModel(tbl);
            tbl.addRow(new Object[]{
                    tID.getText(), tNama.getText(), tHarga.getText()
                    });
            vTabel.setModel(tbl);
            tID.setText("ID Barang/Jasa");
            tNama.setText("Nama Barang/Jasa");
            tHarga.setText("Harga");
             pnMain.removeAll();
              pnMain.add(pnPricelist);
              pnMain.repaint();
              pnMain.revalidate();   
    }//GEN-LAST:event_bSelesaiiMousePressed

    int baris = 0;
    static Object kolom[] = {"ID", "Nama", "Harga"};
    DefaultTableModel tbl = new DefaultTableModel (kolom, baris);       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Palette.Panel bCAncel;
    private Palette.Panel bCancel;
    private Palette.Panel bCancel1;
    private Palette.Panel bCancel2;
    private Palette.Panel bSelesai;
    private Palette.Panel bSelesaii;
    private Palette.Panel bTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnPricelist;
    private javax.swing.JPanel pnTambah;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField tID;
    private javax.swing.JTextField tNama;
    private Palette.JTable_Custom vTabel;
    // End of variables declaration//GEN-END:variables
}
