/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package apkbarber;

import config.koneksi;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alxxstrdy
 */
public class Report extends javax.swing.JPanel {

    /**
     * Creates new form Report
     */
        private Connection conn;
    public Report() {
        initComponents();
        pnBeban.setVisible(false);
        conn = (Connection) koneksi.getConnection();
           
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tanggalAwal = new com.raven.datechooser.DateChooser();
        tAkhir = new com.raven.datechooser.DateChooser();
        pnMain = new javax.swing.JPanel();
        pnSatu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tAwal = new javax.swing.JTextField();
        tAkhie = new javax.swing.JTextField();
        choAwal = new javax.swing.JLabel();
        choAkhie = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnAdd = new Palette.Panel();
        lTambah = new javax.swing.JLabel();
        pnBeban = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        tGaji = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tPeralatan = new javax.swing.JTextField();
        tPerlengkapan = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tAirListrik = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tSewa = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tLainnya = new javax.swing.JTextField();
        btnPrint = new Palette.Panel();
        lTambah1 = new javax.swing.JLabel();
        pnDua = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnPrint = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vPeriode = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        vTotalPen = new javax.swing.JLabel();
        vBbnGaji = new javax.swing.JLabel();
        vBebanPera = new javax.swing.JLabel();
        vBebanPerl = new javax.swing.JLabel();
        vBebanAiLis = new javax.swing.JLabel();
        vTotalBeban = new javax.swing.JLabel();
        vLabaBersih = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        vBebanLain = new javax.swing.JLabel();
        vBebanSewa = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        tanggalAwal.setForeground(new java.awt.Color(2, 131, 145));
        tanggalAwal.setDateFormat("yyyy-MM-dd");
        tanggalAwal.setTextRefernce(tAwal);

        tAkhir.setForeground(new java.awt.Color(2, 131, 145));
        tAkhir.setDateFormat("yyyy-MM-dd");
        tAkhir.setTextRefernce(tAkhie);

        setLayout(new java.awt.CardLayout());

        pnMain.setLayout(new java.awt.CardLayout());

        pnSatu.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        choAwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calendar.png"))); // NOI18N
        choAwal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choAwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                choAwalMousePressed(evt);
            }
        });

        choAkhie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calendar.png"))); // NOI18N
        choAkhie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choAkhie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                choAkhieMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("NEXT ART", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Report1.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("NEXT ART", 1, 14)); // NOI18N
        jLabel16.setText("PILIH PERIODE TANGGAL");

        jLabel17.setFont(new java.awt.Font("NEXT ART", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("LAPORAN");

        btnAdd.setBackground(new java.awt.Color(2, 131, 145));
        btnAdd.setFocusCycleRoot(true);
        btnAdd.setRoundBottomLeft(10);
        btnAdd.setRoundBottomRight(10);
        btnAdd.setRoundTopLeft(10);
        btnAdd.setRoundTopRight(10);
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddMousePressed(evt);
            }
        });

        lTambah.setFont(new java.awt.Font("NEXT ART", 0, 14)); // NOI18N
        lTambah.setForeground(new java.awt.Color(255, 255, 255));
        lTambah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTambah.setText("TAMBAH");
        lTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnAddLayout = new javax.swing.GroupLayout(btnAdd);
        btnAdd.setLayout(btnAddLayout);
        btnAddLayout.setHorizontalGroup(
            btnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );
        btnAddLayout.setVerticalGroup(
            btnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tAwal, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                            .addComponent(tAkhie))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(choAwal)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(choAkhie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choAwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tAkhie, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choAkhie, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        pnBeban.setBackground(new java.awt.Color(255, 255, 255));
        pnBeban.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane2.setBorder(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("TOTAL GAJI KARYAWAN");

        tGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tGajiActionPerformed(evt);
            }
        });
        tGaji.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tGajiKeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("BELANJA PERALATAN");

        tPeralatan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tPeralatanKeyReleased(evt);
            }
        });

        tPerlengkapan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tPerlengkapanKeyReleased(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("BELANJA PERLENGKAPAN");

        tAirListrik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tAirListrikKeyReleased(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("PEMBAYARAN AIR & LISTRIK");

        tSewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tSewaKeyReleased(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("BIAYA SEWA");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("BIAYA LAINNYA");

        tLainnya.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tLainnyaKeyReleased(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(2, 131, 145));
        btnPrint.setFocusCycleRoot(true);
        btnPrint.setRoundBottomLeft(10);
        btnPrint.setRoundBottomRight(10);
        btnPrint.setRoundTopLeft(10);
        btnPrint.setRoundTopRight(10);
        btnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrintMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrintMousePressed(evt);
            }
        });

        lTambah1.setFont(new java.awt.Font("NEXT ART", 0, 14)); // NOI18N
        lTambah1.setForeground(new java.awt.Color(255, 255, 255));
        lTambah1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTambah1.setText("CETAK");
        lTambah1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnPrintLayout = new javax.swing.GroupLayout(btnPrint);
        btnPrint.setLayout(btnPrintLayout);
        btnPrintLayout.setHorizontalGroup(
            btnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lTambah1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );
        btnPrintLayout.setVerticalGroup(
            btnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lTambah1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(tGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(tPeralatan, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tAirListrik, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(tSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(tLainnya, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tPerlengkapan, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(78, 323, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPeralatan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPerlengkapan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tAirListrik, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tLainnya, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout pnBebanLayout = new javax.swing.GroupLayout(pnBeban);
        pnBeban.setLayout(pnBebanLayout);
        pnBebanLayout.setHorizontalGroup(
            pnBebanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        pnBebanLayout.setVerticalGroup(
            pnBebanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnSatuLayout = new javax.swing.GroupLayout(pnSatu);
        pnSatu.setLayout(pnSatuLayout);
        pnSatuLayout.setHorizontalGroup(
            pnSatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSatuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnSatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnBeban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        pnSatuLayout.setVerticalGroup(
            pnSatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSatuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnBeban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnMain.add(pnSatu, "card2");

        pnDua.setBackground(new java.awt.Color(255, 255, 255));

        pnPrint.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LAPORAN");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PENDAPATAN BARBER");

        vPeriode.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        vPeriode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vPeriode.setText("PERIODE TANGGAL");

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("PENDAPATAN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("TOTAL PENDAPATAN");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("BEBAN-BEBAN");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("BEBAN GAJI");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("BEBAN PERALATAN");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("BEBAN PERLENGKAPAN");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("BEBAN AIR DAN LISTRIK");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("TOTAL BEBAN");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("LABA BERSIH");

        vTotalPen.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vTotalPen.setText("NOMINAL");

        vBbnGaji.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vBbnGaji.setText("NOMINAL");

        vBebanPera.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vBebanPera.setText("NOMINAL");

        vBebanPerl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vBebanPerl.setText("NOMINAL");

        vBebanAiLis.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vBebanAiLis.setText("NOMINAL");

        vTotalBeban.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vTotalBeban.setText("NOMINAL");

        vLabaBersih.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vLabaBersih.setText("NOMINAL");

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(191, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("BEBAN LAINNYA");

        vBebanLain.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vBebanLain.setText("NOMINAL");

        vBebanSewa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vBebanSewa.setText("NOMINAL");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setText("BEBAN SEWA");

        javax.swing.GroupLayout pnPrintLayout = new javax.swing.GroupLayout(pnPrint);
        pnPrint.setLayout(pnPrintLayout);
        pnPrintLayout.setHorizontalGroup(
            pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
            .addComponent(vPeriode, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPrintLayout.createSequentialGroup()
                .addGroup(pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnPrintLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vBebanSewa)
                            .addComponent(vBebanLain)
                            .addComponent(vBbnGaji)
                            .addComponent(vBebanPera)
                            .addComponent(vBebanPerl)
                            .addComponent(vBebanAiLis)
                            .addGroup(pnPrintLayout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(vTotalPen))))
                    .addGroup(pnPrintLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vTotalBeban)
                            .addComponent(vLabaBersih))))
                .addGap(100, 100, 100))
            .addGroup(pnPrintLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPrintLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPrintLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPrintLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        pnPrintLayout.setVerticalGroup(
            pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrintLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(vPeriode)
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vTotalPen))
                .addGap(55, 55, 55)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(vBbnGaji))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(vBebanPera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(vBebanPerl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(vBebanAiLis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(vBebanSewa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(vBebanLain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPrintLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14))
                    .addGroup(pnPrintLayout.createSequentialGroup()
                        .addComponent(vTotalBeban)
                        .addGap(11, 11, 11)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vLabaBersih)))
                .addContainerGap(444, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pnPrint);

        javax.swing.GroupLayout pnDuaLayout = new javax.swing.GroupLayout(pnDua);
        pnDua.setLayout(pnDuaLayout);
        pnDuaLayout.setHorizontalGroup(
            pnDuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDuaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(478, Short.MAX_VALUE))
        );
        pnDuaLayout.setVerticalGroup(
            pnDuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDuaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pnMain.add(pnDua, "card2");

        add(pnMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        btnAdd.setBackground(new Color (2,154,170));
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        btnAdd.setBackground(new Color (2,131,145));
    }//GEN-LAST:event_btnAddMouseExited

    private void btnAddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMousePressed
        pnBeban.setVisible(true);
    }//GEN-LAST:event_btnAddMousePressed

    private void tGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tGajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tGajiActionPerformed

    private void btnPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseEntered
        btnPrint.setBackground(new Color (2,154,170));
    }//GEN-LAST:event_btnPrintMouseEntered

    private void btnPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseExited
        btnPrint.setBackground(new Color (2,131,145));
    }//GEN-LAST:event_btnPrintMouseExited

    private void btnPrintMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMousePressed
        ambildata();
        masukdata();


        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Laporan");
        
        job.setPrintable(new Printable(){
        public int print(Graphics pg, PageFormat pf, int pageNum){
            pf.setOrientation(PageFormat.LANDSCAPE);
           if(pageNum>0){
            return Printable.NO_SUCH_PAGE;
           }
           Graphics2D g2 = (Graphics2D)pg;
           g2.translate(pf.getImageableX(), pf.getImageableY());
           g2.scale(0.75, 0.75);
           
           pnPrint.print(g2);
           
           return Printable.PAGE_EXISTS;
        }
        });    
        
        boolean ok = job.printDialog();
        if(ok){
            try{
                
                job.print();
            } catch (PrinterException x){
            x.printStackTrace();}
        }    
    }//GEN-LAST:event_btnPrintMousePressed

    private void choAwalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choAwalMousePressed
        tanggalAwal.showPopup();
    }//GEN-LAST:event_choAwalMousePressed

    private void choAkhieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choAkhieMousePressed
        tAkhir.showPopup();
    }//GEN-LAST:event_choAkhieMousePressed

    private void tGajiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tGajiKeyReleased
        String gaji = tGaji.getText().replaceAll("[^\\d]", "");
        double Rp = Double.parseDouble(gaji);
        DecimalFormat df = new DecimalFormat("#,###,###");
        tGaji.setText("Rp." + df.format(Rp)); 
    }//GEN-LAST:event_tGajiKeyReleased

    private void tPeralatanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPeralatanKeyReleased
        String gaji = tPeralatan.getText().replaceAll("[^\\d]", "");
        double Rp = Double.parseDouble(gaji);
        DecimalFormat df = new DecimalFormat("#,###,###");
        tPeralatan.setText("Rp." + df.format(Rp)); 
    }//GEN-LAST:event_tPeralatanKeyReleased

    private void tPerlengkapanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPerlengkapanKeyReleased
        String gaji = tPerlengkapan.getText().replaceAll("[^\\d]", "");
        double Rp = Double.parseDouble(gaji);
        DecimalFormat df = new DecimalFormat("#,###,###");
        tPerlengkapan.setText("Rp." + df.format(Rp)); 
    }//GEN-LAST:event_tPerlengkapanKeyReleased

    private void tAirListrikKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tAirListrikKeyReleased
        String gaji = tAirListrik.getText().replaceAll("[^\\d]", "");
        double Rp = Double.parseDouble(gaji);
        DecimalFormat df = new DecimalFormat("#,###,###");
        tAirListrik.setText("Rp." + df.format(Rp)); 
    }//GEN-LAST:event_tAirListrikKeyReleased

    private void tSewaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSewaKeyReleased
        String gaji = tSewa.getText().replaceAll("[^\\d]", "");
        double Rp = Double.parseDouble(gaji);
        DecimalFormat df = new DecimalFormat("#,###,###");
        tSewa.setText("Rp." + df.format(Rp)); 
    }//GEN-LAST:event_tSewaKeyReleased

    private void tLainnyaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tLainnyaKeyReleased
        String gaji = tLainnya.getText().replaceAll("[^\\d]", "");
        double Rp = Double.parseDouble(gaji);
        DecimalFormat df = new DecimalFormat("#,###,###");
        tLainnya.setText("Rp." + df.format(Rp)); 
    }//GEN-LAST:event_tLainnyaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Palette.Panel btnAdd;
    private Palette.Panel btnPrint;
    private javax.swing.JLabel choAkhie;
    private javax.swing.JLabel choAwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lTambah;
    private javax.swing.JLabel lTambah1;
    private javax.swing.JPanel pnBeban;
    private javax.swing.JPanel pnDua;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnPrint;
    private javax.swing.JPanel pnSatu;
    private javax.swing.JTextField tAirListrik;
    private javax.swing.JTextField tAkhie;
    private com.raven.datechooser.DateChooser tAkhir;
    private javax.swing.JTextField tAwal;
    private javax.swing.JTextField tGaji;
    private javax.swing.JTextField tLainnya;
    private javax.swing.JTextField tPeralatan;
    private javax.swing.JTextField tPerlengkapan;
    private javax.swing.JTextField tSewa;
    private com.raven.datechooser.DateChooser tanggalAwal;
    private javax.swing.JLabel vBbnGaji;
    private javax.swing.JLabel vBebanAiLis;
    private javax.swing.JLabel vBebanLain;
    private javax.swing.JLabel vBebanPera;
    private javax.swing.JLabel vBebanPerl;
    private javax.swing.JLabel vBebanSewa;
    private javax.swing.JLabel vLabaBersih;
    private javax.swing.JLabel vPeriode;
    private javax.swing.JLabel vTotalBeban;
    private javax.swing.JLabel vTotalPen;
    // End of variables declaration//GEN-END:variables
private void ambildata(){
    String awal = tAwal.getText();
    String akhir = tAkhie.getText();
    try {
                String sql = "SELECT SUM(total_harga) AS total FROM transaksi WHERE tgl_transaksi BETWEEN ? AND ?;";
                try (PreparedStatement st = conn.prepareStatement(sql)) {
                    st.setString(1, awal);
                    st.setString(2, akhir);
                    ResultSet rs = st.executeQuery();

                    while (rs.next()) {
                        String total = rs.getString("total").replaceAll("[^\\d]", "");
                        double Rp = Double.parseDouble(total);
                        DecimalFormat df = new DecimalFormat("#,###,###");
                        vTotalPen.setText("Rp." + df.format(Rp)); ;
                        


                    }
                }
            } catch (SQLException e) {
                Logger.getLogger(Reservasi.class.getName()).log(Level.SEVERE, null, e);
            }
}

    private void masukdata() {
        String awal = tAwal.getText();
        String akhir = tAkhie.getText();
        vPeriode.setText(awal + " - " + akhir);
        if(tGaji.getText().equals(null)){
            vBbnGaji.setText("Rp.0");
        }else if (!tGaji.getText().equals(null)){
            vBbnGaji.setText(tGaji.getText());
        }
        
        if(tPeralatan.getText().equals(null)){
            vBebanPera.setText("Rp.0");
        }else if (!tPeralatan.getText().equals(null)){
            vBebanPera.setText(tPeralatan.getText());
        }
        
        if(tPerlengkapan.getText().equals(null)){
            vBebanPerl.setText("Rp.0");
        }else if (!tPerlengkapan.getText().equals(null)){
            vBebanPerl.setText(tPerlengkapan.getText());
        }
        
        
        if(tAirListrik.getText().equals(null)){
            vBebanAiLis.setText("Rp.0");
        }else if (!tAirListrik.getText().equals(null)){
            vBebanAiLis.setText(tAirListrik.getText());
        }
        
        if(tSewa.getText().equals(null)){
            vBebanSewa.setText("Rp.0");
        }else if (!tSewa.getText().equals(null)){
            vBebanSewa.setText(tSewa.getText());
        }
        
        
        if(tLainnya.getText().equals(null)){
            vBebanLain.setText("Rp.0");
        }else if (!tLainnya.getText().equals(null)){
            vBebanLain.setText(tLainnya.getText());
        }
        
        int gaji = Integer.parseInt(tGaji.getText().replace(",", "").substring(3));
        int peralatan = Integer.parseInt(tPeralatan.getText().replace(",", "").substring(3));
        int perlengkapan = Integer.parseInt(tPerlengkapan.getText().replace(",", "").substring(3));
        int airlis = Integer.parseInt(tAirListrik.getText().replace(",", "").substring(3));
        int sewa = Integer.parseInt(tSewa.getText().replace(",", "").substring(3));
        int lainnya = Integer.parseInt(tGaji.getText().replace(",", "").substring(3));
        int beban = gaji + peralatan + perlengkapan + airlis + sewa + lainnya;
        vTotalBeban.setText(Integer.toString(beban));
        String vbeban = vTotalBeban.getText().replaceAll("[^\\d]", "");
        double Rp = Double.parseDouble(vbeban);
        DecimalFormat df = new DecimalFormat("#,###,###");
        vTotalBeban.setText("Rp." + df.format(Rp)); 
        int total = Integer.parseInt(vTotalPen.getText().replace(",", "").substring(3));
        int laba = total - beban;
        vLabaBersih.setText(Integer.toString(laba));
        String laber = vLabaBersih.getText().replaceAll("[^\\d]", "");
        double Rup = Double.parseDouble(laber);
        DecimalFormat def = new DecimalFormat("#,###,###");
        vLabaBersih.setText("Rp." + def.format(Rup)); 
    }

    
    
}
